server:
  port: 8888


mybatis:
  type-aliases-package: com.auth.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    connect-timeout: 10000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac-auth?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql